# Generated by Django 4.1.7 on 2023-04-21 00:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paleta',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
