# Generated by Django 4.1.7 on 2023-04-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_rename_tipo_paleta_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paleta',
            old_name='modelo',
            new_name='tipo',
        ),
    ]
