# Generated by Django 4.1.7 on 2023-04-25 23:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_rename_tipo_paleta_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=20)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('stock', models.IntegerField()),
                ('fecha_de_carga', models.DateField()),
            ],
        ),
    ]
