# Generated by Django 4.1.7 on 2023-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_gasto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paleta',
        ),
        migrations.RenameField(
            model_name='gasto',
            old_name='marca',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='gasto',
            old_name='modelo',
            new_name='tipo',
        ),
        migrations.AddField(
            model_name='gasto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
